
apiVersion: v1
kind: Secret
metadata:
  name: review-db-url
  namespace: book-explorer
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@postgres:5432/reviews
  # password: postgres
  #user : postgres
  #host: postgres
  #database: reviews
