apiVersion: apps/v1
kind: Deployment
metadata: { name: catalog-svc, namespace: book-explorer }
spec:
  replicas: 1
  selector: { matchLabels: { app: catalog-svc } }
  template:
    metadata: { labels: { app: catalog-svc } }
    spec:
      containers:
      - name: app
        image: pegahsm/catalog-svc:4.0
        ports: [{ containerPort: 8000 }]
        resources:
          requests: { cpu: "100m", memory: "128Mi" }
          limits:   { cpu: "500m", memory: "256Mi" }
        readinessProbe: { httpGet: { path: "/docs", port: 8000 }, initialDelaySeconds: 5 }
        livenessProbe:  { httpGet: { path: "/docs", port: 8000 }, initialDelaySeconds: 10 }
---
apiVersion: v1
kind: Service
metadata: { name: catalog-svc, namespace: book-explorer }
spec:
  selector: { app: catalog-svc }
  ports: [{ port: 80, targetPort: 8000 }]
